source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'jquery-rails'
gem 'haml-rails', '~> 0.4'

gem 'pg'

gem 'thin'  # If on Heroku, or prototyping on Ubuntu
# gem 'pow'  # If rapid prototyping in Mac OS X

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer', :platforms => :ruby # For Ubuntu
end

group :development do
  gem 'brice'
  gem 'pry-rails', '~> 0.2.2'
  gem 'pry-doc', '~> 0.4.4'
  gem 'awesome_print'
end

group :development, :test do
  gem 'sqlite3' # For default rails, prototyping, and testing

  gem 'rspec-rails', '>= 2.11.1'
  gem 'jasminerice'
  gem 'rb-inotify', '~> 0.8.8', :require => false # If on Ubuntu
  gem 'rb-fsevent', :require => false # If on OSX
  gem 'guard-rspec', '~> 2.4.0'
  gem 'guard-jasmine'
end

group :test do
  gem 'factory_girl_rails', '>= 1.6.0'
  gem 'cucumber-rails', '>= 1.2.1'
  gem 'capybara', '>= 2.0.0'
  gem 'database_cleaner'
end

# To avoid installing these gems locally, run bundle using: --without production
group :production do
end
