source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'jquery-rails'
gem 'haml-rails', '~> 0.3.5'

### Database ###
gem 'sqlite3' # For default rails, prototyping, and testing
gem 'pg'

### Web server ###
#gem 'thin'  # If heroku
#gem 'pow'  # If rapid prototyping in Mac OS X

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer', :platforms => :ruby # For Ubuntu
end

group :development, :test do
  gem 'rspec-rails', '>= 2.8.1'
  gem 'rb-inotify', '~> 0.8.8', :require => false # If on Ubuntu
  gem 'rb-fsevent', :require => false # If on OSX
  gem 'guard-rspec'
end

group :test do
  gem 'factory_girl_rails', '>= 1.6.0'
  gem 'cucumber-rails', '>= 1.2.1'
  gem 'capybara', '>= 1.1.2'
  gem 'database_cleaner'
end

group :production do
end
